version: '3.8'

networks:
  job-management-network:
    driver: bridge
volumes:
  prometheus_data:
  grafana_data:

services:
  postgres:
    container_name: job-management-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=job-management
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - job-management-network
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3004:3000
    networks:
      - job-management-network
